#!/usr/bin/env python3
"""TCNN_RDNA4_P3B1C_FP16_BACKWARD_001 report assembler."""
import hashlib,json,pathlib,subprocess
R=pathlib.Path(__file__).resolve().parents[1]; P=R/"phase3b1_reports"; BASE="b59d569e5c662e8738f6af929e122c954ec68d7c"; MARKER="TCNN_RDNA4_P3B1C_FP16_BACKWARD_001"
raw=json.loads((P/"phase3b1c_fp16_backward_raw.json").read_text());cap=json.loads((P/"phase3b1c_backward_capability.json").read_text())
regroot=P/"phase3b1c_fp32_regression.json";a1=json.loads((regroot/"phase3a1_regression/phase3a1_validation.json").read_text());a4=json.loads((regroot/"phase3a4_validation.json").read_text())
hist=["PHASE3B1A_FP16_CAPABILITY.md","phase3b1a_fp16_capability.json","PHASE3B1B_FP16_FORWARD.md","phase3b1b_fp16_forward.json","PHASE3B1B1_FP16_FORWARD_HARDENING.md","phase3b1b1_fp16_forward_hardening.json"]
def sha(b):return hashlib.sha256(b).hexdigest()
historical={}
for n in hist:
 now=(P/n).read_bytes(); old=subprocess.check_output(["git","show",f"{BASE}:phase3b1_reports/{n}"],cwd=R)
 historical[n]={"sha256":sha(now),"base_sha256":sha(old),"byte_identical":now==old}
changed=subprocess.check_output(["git","diff","--name-only",BASE],cwd=R,text=True).splitlines()+subprocess.check_output(["git","ls-files","--others","--exclude-standard"],cwd=R,text=True).splitlines()
sources=[x for x in changed if x.endswith((".cu",".cpp",".h",".py",".sh")) or x=="bindings/torch/setup.py"]
markers={x:MARKER in (R/x).read_text(errors="replace") for x in sources}
frozen=["src/hipblaslt_mlp.cu","src/hipblaslt_relu_biasgrad.cu","include/tiny-cuda-nn/networks/hipblaslt_mlp.h"]
frozen_diff=subprocess.check_output(["git","diff","--name-only",BASE,"--",*frozen],cwd=R,text=True).splitlines()
algos={}
for c in cap["cases"]:
 for f in c["fresh_runs"]:
  a=f["algorithm"];algos[str(a["index"])]= {"index":a["index"],"kernel":a["kernel"],"solution":a["solution"],"workspace":a["workspace"]}
doc={"marker":MARKER,"branch":subprocess.check_output(["git","branch","--show-current"],cwd=R,text=True).strip(),"base_commit":BASE,"decision":raw["decision"],"gradient_contract":{"dL_doutput":"FP16","internal_dL_dinput":"FP16","external_dL_dinput":"FP32 after Identity encoding","internal_dW_db":"FP32","native_parameter_gradient":"FP16 single final conversion","pytorch_master_parameters_and_gradients":"FP32","dynamic_loss_scaling":"not implemented"},"capability":{"result":cap["decision"],"summary":cap["summary"],"algorithms":list(algos.values()),"workspace_bytes":sorted({x["workspace"] for x in algos.values()})},"functional":raw,"fp32_regression":{"phase3a1":a1.get("result","PASS"),"phase3a4":a4["result"],"paths":[str(regroot/"phase3a1_regression/phase3a1_validation.json"),str(regroot/"phase3a4_validation.json")]},"historical_reports":historical,"marker_audit":{"files":markers,"all":all(markers.values())},"production_diff":{"changed":changed,"frozen_phase3a4_fp32_files":frozen,"frozen_diff":frozen_diff,"frozen_unchanged":not frozen_diff},"scratch":{"live":raw["multistream"]["after"]["scratch_bytes_live"],"peak":raw["multistream"]["after"]["scratch_bytes_peak"]}}
if not(all(x["byte_identical"] for x in historical.values()) and doc["marker_audit"]["all"] and doc["production_diff"]["frozen_unchanged"] and a4["result"]=="PASS" and raw["decision"]=="PROCEED_TO_3B1D"):doc["decision"]="PHASE3B1C_BLOCKED"
(P/"phase3b1c_fp16_backward.json").write_text(json.dumps(doc,indent=2)+"\n")
m=raw["maxima"]; md=["# Phase 3B1-C – FP16 Backward-Basispfad","",f"Marker: `{MARKER}`","",f"**Entscheidung: `{doc['decision']}`**","","## Vertrag","","- FP16: Operanden, gespeicherte Aktivierungen, dZ, internes dX und nativer Parametergradientpuffer.","- FP32: hipBLASLt-Akkumulation, dW/db-Scratch und deterministische Biasreduktion.","- Python/PyTorch: FP32-Masterparameter und FP32-Gradienten; einmalige Konvertierung des nativen FP16-Gradienten.","- Overwrite, Accumulate und Ignore bestanden; keine FP16-Atomics und kein dynamisches Loss Scaling.","","## Capability und Numerik","",f"- Capability: `{cap['decision']}`; {cap['summary']['cases']} Signaturen in {cap['summary']['fresh_processes']} Fresh Processes.",f"- Ausgewählte Algorithmen: {len(algos)} eindeutige Lösungen; Workspace stets 0 Byte (vollständig im JSON).",f"- Funktionale Fälle: {raw['passed_cases']}/{raw['functional_cases']} bestanden.",f"- dX max_abs={m['dx']['max_abs']}, nL2={m['dx']['normalized_l2']}, ULP außerhalb Near-zero={m['dx']['max_ulp_outside_near_zero']}",f"- dW max_abs={m['dw']['max_abs']}, nL2={m['dw']['normalized_l2']}, ULP außerhalb Near-zero={m['dw']['max_ulp_outside_near_zero']}",f"- db max_abs={m['db']['max_abs']}, nL2={m['db']['normalized_l2']}, ULP außerhalb Near-zero={m['db']['max_ulp_outside_near_zero']}",f"- dZ max_abs={m['dz']['max_abs']}, Maskenabweichungen={raw['relu_mask_mismatches']}","","## Invarianten","",f"- Echter Multistream-Test: `{raw['multistream']['passed']}` (2 Streams, 64+64 asynchrone Runden).",f"- Dynamische Batchfolge: `{raw['dynamic_batches']['passed']}`; zweiter Durchlauf ohne neue Pläne/Heuristiken/Handles/Deskriptoren.",f"- Scratch live/peak: {doc['scratch']['live']}/{doc['scratch']['peak']} Byte.",f"- Phase 3A1 / 3A4: `{doc['fp32_regression']['phase3a1']}` / `{doc['fp32_regression']['phase3a4']}`.",f"- Historische A/B/B1-Berichte bytegleich: `{all(x['byte_identical'] for x in historical.values())}`.",f"- Marker-Audit: `{doc['marker_audit']['all']}`.",f"- Eingefrorene Phase-3A4-/FP32-Kerneldateien unverändert: `{doc['production_diff']['frozen_unchanged']}`.","","Alle Einzelfälle, Algorithmen, Counter, Toleranzen, Hashes und Diffpfade stehen im JSON-Bericht.",""]
(P/"PHASE3B1C_FP16_BACKWARD.md").write_text("\n".join(md));print(doc["decision"])
