#!/usr/bin/env python3
"""TCNN_RDNA4_P3B1D_FP16_TRAINING_001 compact fail-closed report."""
import hashlib,json,pathlib,subprocess
R=pathlib.Path(__file__).resolve().parents[1];P=R/"phase3b1_reports";BASE="09b6a777bda2b4ed4d14bf22e265b5fb8f83fb65";MARKER="TCNN_RDNA4_P3B1D_FP16_TRAINING_001"
def load(p):return json.loads(pathlib.Path(p).read_text())
def sha(x):return hashlib.sha256(x).hexdigest()
rawp=pathlib.Path("/tmp/phase3b1d_fp16_training_raw.json");raw=load(rawp);baseline=load("/tmp/phase3b1d_fresh_gpu_baseline.json");a1=load("/tmp/phase3b1d_fp32_regression/phase3a1_regression/phase3a1_validation.json");a4=load("/tmp/phase3b1d_fp32_regression/phase3a4_validation.json");b=load("/tmp/phase3b1d_forward_b.json");b1=load("/tmp/phase3b1d_forward_b1.json")
tracked=subprocess.check_output(["git","ls-tree","-r","--name-only",BASE,"phase3b1_reports"],cwd=R,text=True).splitlines();hist={}
for rel in tracked:
 scoped=rel.lower().removeprefix("phase3b1_reports/")
 if not scoped.startswith(("phase3b1a","phase3b1b","phase3b1c")):continue
 old=subprocess.check_output(["git","show",f"{BASE}:{rel}"],cwd=R);now=(R/rel).read_bytes() if (R/rel).is_file() else b"";hist[rel]={"sha256":sha(now),"base_sha256":sha(old),"byte_identical":now==old}
changed=subprocess.check_output(["git","diff","--name-only",BASE],cwd=R,text=True).splitlines()+subprocess.check_output(["git","ls-files","--others","--exclude-standard"],cwd=R,text=True).splitlines();production=[x for x in changed if x.startswith(("src/","include/","bindings/"))];sources=[x for x in changed if x.endswith((".py",".sh",".md")) and not x.startswith("phase3b1_reports/PHASE3B1D_FP16_TRAINING.md")];markers={x:MARKER in (R/x).read_text(errors="replace") for x in sources}
b_forward=all(x.get("passed") is True for x in b.get("cases",[])+b.get("adversarial",[])) and b.get("counters",{}).get("warm_cache_passed") is True and b.get("fresh_processes",{}).get("passed") is True and b.get("memory_stability",{}).get("passed") is True and b.get("two_streams",{}).get("passed") is True
checks={"training_raw":raw.get("decision")=="PROCEED_TO_3B1E","fresh_gpu_baseline":baseline.get("decision")=="PROCEED_TO_3B1D" and baseline.get("passed_cases")==baseline.get("functional_cases")==296,"quantized_reference":raw.get("quantized_training_reference",{}).get("passed") is True,"short_training":raw.get("short_training",{}).get("passed") is True,"gradient_accumulation":raw.get("gradient_accumulation",{}).get("passed") is True,"static_scaling":raw.get("static_loss_scaling",{}).get("passed") is True,"dynamic_scaling":raw.get("dynamic_loss_scaling",{}).get("passed") is True,"long_runs":raw.get("long_runs",{}).get("passed") is True and raw["long_runs"].get("total_steps")==3000,"checkpoint_resume":raw.get("checkpoint_resume",{}).get("passed") is True and len(raw["checkpoint_resume"].get("protocols",[]))==4,"stream_training":raw.get("stream_training",{}).get("passed") is True,"phase3a1":a1.get("result")=="PASS","phase3a4":a4.get("result")=="PASS","phase3b1b_forward_only":b_forward,"phase3b1b1":b1.get("functional_decision")=="HARDENING_FUNCTIONAL_PASS","c1a_envelope":baseline.get("maxima") is not None and baseline.get("direct_dz_mask_mismatches")==0,"historical_reports":len(hist)>0 and all(x["byte_identical"] for x in hist.values()),"production_unchanged":not production,"marker_audit":len(markers)>0 and all(markers.values())}
decision="PROCEED_TO_3B1E" if all(checks.values()) else "PHASE3B1D_BLOCKED";rb=rawp.read_bytes();mx=raw["quantized_training_reference"]
doc={"marker":MARKER,"base_commit":BASE,"branch":subprocess.check_output(["git","branch","--show-current"],cwd=R,text=True).strip(),"decision":decision,"gates":checks,"raw_data":{"absolute_path":str(rawp.resolve()),"size_bytes":len(rb),"sha256":sha(rb),"short_training_cases":raw["short_training"]["count"],"long_runs":raw["long_runs"]["count"],"long_steps":raw["long_runs"]["total_steps"]},"optimizers":["SGD","Adam"],"loss_scaling":{"static":raw["static_loss_scaling"],"dynamic":raw["dynamic_loss_scaling"]},"checkpoint_resume":raw["checkpoint_resume"],"numerical_maxima":{"reference_dx":mx["dx"],"reference_native_gradient":mx["native_fp16_gradient"],"accumulation_gradient_max_abs":raw["gradient_accumulation"]["max_gradient_abs"],"accumulation_parameter_max_abs":raw["gradient_accumulation"]["max_parameter_abs"]},"memory_cache_descriptor":{"stream_training":raw["stream_training"],"long_runs":[{"optimizer":x["optimizer"],"memory_warm":x["memory_warm"],"memory_end":x["memory_end"],"counters_warm":x["counters_warm"],"counters_end":x["counters_end"]} for x in raw["long_runs"]["runs"]]},"regressions":{"phase3a1":"PASS","phase3a4":"PASS","phase3b1b_forward":"PASS","phase3b1b_legacy_overall":b.get("decision"),"phase3b1b_legacy_note":"forward-only tests pass; obsolete expected-backward-rejection is false after 3B1-C","phase3b1b1":"PASS","phase3b1c_c1_c1a":"PASS via fresh 296/296 C1a envelope"},"historical_reports":hist,"production_changed":production,"marker_audit":markers}
(P/"phase3b1d_fp16_training.json").write_text(json.dumps(doc,indent=2)+"\n")
lines=["# Phase 3B1-D – FP16 Training, Loss Scaling und Checkpoint/Resume","",f"Marker: `{MARKER}`","",f"**Entscheidung: `{decision}`**","","## Ergebnis","",f"- Fresh-GPU-Baseline: 296/296.",f"- Kurztrainings: {raw['short_training']['count']} × 50 Schritte; SGD und Adam.",f"- Langläufe: {raw['long_runs']['count']} × 1000 = {raw['long_runs']['total_steps']} Schritte.",f"- Gradient Accumulation: `{raw['gradient_accumulation']['passed']}`.",f"- Statisches Loss Scaling 1/8/128/1024/8192: `{raw['static_loss_scaling']['passed']}`.",f"- Dynamisches Loss Scaling, Overflow-Skip und Recovery: `{raw['dynamic_loss_scaling']['passed']}`.",f"- Checkpoint/Resume: 4/4 bitidentisch in frischen Prozessen.",f"- Zwei-Stream-Training: `{raw['stream_training']['passed']}`.","","## Regressionen","",f"- Phase 3A1 / 3A4: PASS / PASS.",f"- Phase 3B1-B Forward: PASS; der historische Gesamtstatus `{b.get('decision')}` stammt ausschließlich vom heute überholten Vertrag 'Backward muss abgewiesen werden'.",f"- Phase 3B1-B1: PASS; C/C1/C1a-Hülle: 296/296.",f"- Historische Reports bytegleich: `{checks['historical_reports']}`; Produktionscode unverändert: `{checks['production_unchanged']}`.","","Der große Rohreport bleibt lokal und ist im kompakten JSON mit absolutem Pfad, Größe und SHA256 referenziert.",""]
(P/"PHASE3B1D_FP16_TRAINING.md").write_text("\n".join(lines));print(decision)
