#!/usr/bin/env python3
"""TCNN_RDNA4_P3B1D1_TRAINING_AUDIT_001 fail-closed finalizer."""
import copy,hashlib,json,pathlib,subprocess
R=pathlib.Path(__file__).resolve().parents[1];P=R/"phase3b1_reports";BASE="c3d01aa5eb4b6f4cc5f2f5eb9a676cf1a4d56748";C1A_BASE="09b6a777bda2b4ed4d14bf22e265b5fb8f83fb65";C1A_SHA="bdefbdfdba2ceade2b5fecef94d2c5094db5381188f2a74c6cb5a356526e79de";BASELINE_SHA="e1e969bda7278d9ea37b5c43096e7cda1c784348f993bfb923c9d9190fba5ce3";MARKER="TCNN_RDNA4_P3B1D1_TRAINING_AUDIT_001"
def load(x):return json.loads(pathlib.Path(x).read_text())
def sha(x):return hashlib.sha256(x).hexdigest()
rawp=pathlib.Path("/tmp/phase3b1d1_training_audit_raw.json");baselinep=pathlib.Path("/tmp/phase3b1d_fresh_gpu_baseline.json");raw=load(rawp);baseline=load(baselinep);c1a_path=P/"phase3b1c1a_final_audit.json";c1_envelope_path=P/"phase3b1c1_backward_audit_hardening.json";envelope=load(c1_envelope_path)["prospective_phase3b1d_regression_envelope"]
tracked=subprocess.check_output(["git","ls-tree","-r","--name-only",BASE,"phase3b1_reports"],cwd=R,text=True).splitlines();historical={}
for rel in tracked:
 scoped=rel.lower().removeprefix("phase3b1_reports/")
 if not scoped.startswith(("phase3b1a","phase3b1b","phase3b1c","phase3b1d")) or scoped.startswith("phase3b1d1"):continue
 old=subprocess.check_output(["git","show",f"{BASE}:{rel}"],cwd=R);now=(R/rel).read_bytes() if (R/rel).is_file() else b"";historical[rel]={"base_sha256":sha(old),"current_sha256":sha(now),"byte_identical":old==now}
changed=subprocess.check_output(["git","diff","--name-only",BASE],cwd=R,text=True).splitlines()+subprocess.check_output(["git","ls-files","--others","--exclude-standard"],cwd=R,text=True).splitlines();production=[x for x in changed if x.startswith(("src/","include/","bindings/"))];sources=[x for x in changed if x.endswith((".py",".sh"))];markers={x:MARKER in (R/x).read_text(errors="replace") for x in sources}
def evaluate(test,base):
 checks={};st=test.get("static_checkpoint_resume",{});cmp=st.get("comparisons",{});meta=st.get("checkpoint_metadata",{});rng=test.get("rng_resume",{});event=test.get("event_chain_training",{});ranges=test.get("range_tests",{});overflow=ranges.get("finite_to_fp16_overflow",{});under=ranges.get("underflow_rescue",{})
 checks["static_metadata_and_active_scale"]=st.get("passed") is True and meta.get("scaling_mode")=="static" and meta.get("static_loss_scale")==128.0 and st.get("native_backward_active_scale")==128.0 and all(cmp.get(k) is True for k in ("parameters","gradients","optimizer_state","loss","step","active_loss_scale"))
 checks["complete_rng_resume"]=rng.get("passed") is True and rng.get("cuda_device_count")==1 and all(cmp.get(k) is True for k in ("cpu_rng","cuda_rng_all","custom_generator","post_resume_random_sequence"))
 checks["event_chain_training"]=event.get("passed") is True and event.get("rounds")==64 and event.get("terminal_sync_only") is True and event.get("parameter_max_abs",1)>-1 and event.get("loss_max_abs",1)>-1 and event.get("counters_before")==event.get("counters_after")
 checks["underflow_rescue"]=under.get("passed") is True and under.get("inputs_finite") is True and under.get("scale128_rescued_count",0)>0 and under.get("after_unscale_max_abs_vs_fp32_quantized_reference",1)<=2e-3
 required=("inputs_finite","unscaled_loss_finite","scaled_loss_finite","fp32_internal_gradient_finite","native_fp16_gradient_nonfinite","step_skipped","recovery_passed");checks["finite_overflow"]=overflow.get("passed") is True and all(overflow.get(k) is True for k in required)
 checks["raw_decision"]=test.get("decision")=="AUDIT_TEST_PASS"
 checks["c1a_identity"]=C1A_BASE=="09b6a777bda2b4ed4d14bf22e265b5fb8f83fb65" and sha(baselinep.read_bytes())==BASELINE_SHA and sha(c1a_path.read_bytes())==C1A_SHA
 maxima=base.get("maxima");numeric=isinstance(maxima,dict)
 if numeric:
  for kind in ("dx","dw","db","dz"):
   m=maxima.get(kind);numeric=numeric and isinstance(m,dict) and all(m.get(k,float("inf"))<=v for k,v in envelope[kind].items()) and m.get("nan")==0 and m.get("inf")==0
 checks["c1a_numerical_envelope"]=numeric and base.get("direct_dz_mask_mismatches")==0 and maxima["dz"].get("max_abs")==0 and maxima["dz"].get("max_ulp")==0
 checks["historical_hashes"]=len(historical)>0 and all(x["byte_identical"] for x in historical.values());checks["production_unchanged"]=not production;checks["marker_audit"]=len(markers)>0 and all(markers.values())
 return checks,all(checks.values())
checks,passed=evaluate(raw,baseline);mutations=[]
def mutate(name,fn):
 tr,bl=copy.deepcopy(raw),copy.deepcopy(baseline);fn(tr,bl);ck,ok=evaluate(tr,bl);mutations.append({"name":name,"decision":"PROCEED_TO_3B1E_AUDITED_FINAL" if ok else "PHASE3B1D1_BLOCKED","passed":ok is False,"failed_checks":[k for k,v in ck.items() if not v]})
mutate("static_metadata_128_active_scale_1",lambda t,b:t["static_checkpoint_resume"].__setitem__("native_backward_active_scale",1.0));mutate("cpu_rng_not_restored",lambda t,b:t["static_checkpoint_resume"]["comparisons"].__setitem__("cpu_rng",False));mutate("c1a_dx_max_abs_above_envelope",lambda t,b:b["maxima"]["dx"].__setitem__("max_abs",envelope["dx"]["max_abs"]*2));mutate("event_chain_failed",lambda t,b:t["event_chain_training"].__setitem__("passed",False));mutate("finite_overflow_inputs_not_finite",lambda t,b:t["range_tests"]["finite_to_fp16_overflow"].__setitem__("inputs_finite",False))
decision="PROCEED_TO_3B1E_AUDITED_FINAL" if passed and all(x["passed"] for x in mutations) else "PHASE3B1D1_BLOCKED";rb=rawp.read_bytes();doc={"marker":MARKER,"base_commit":BASE,"decision":decision,"gates":checks,"manipulation_tests":mutations,"static_checkpoint_resume":raw["static_checkpoint_resume"],"rng_resume":raw["rng_resume"],"event_chain_training":raw["event_chain_training"],"range_tests":raw["range_tests"],"c1a_gate":{"bound_commit":C1A_BASE,"baseline_path":str(baselinep),"baseline_expected_sha256":BASELINE_SHA,"baseline_actual_sha256":sha(baselinep.read_bytes()),"report_path":str(c1a_path.resolve()),"expected_sha256":C1A_SHA,"actual_sha256":sha(c1a_path.read_bytes()),"envelope":envelope,"observed":baseline["maxima"],"direct_mask_mismatches":baseline["direct_dz_mask_mismatches"]},"raw_data":{"absolute_path":str(rawp),"size_bytes":len(rb),"sha256":sha(rb)},"historical_reports":historical,"production_changed":production,"marker_audit":markers,"legacy_phase3b1b_contract":"unchanged; historical forward-only runner still expects backward rejection"}
(P/"phase3b1d1_training_audit_hardening.json").write_text(json.dumps(doc,indent=2)+"\n");lines=["# Phase 3B1-D1 – FP16 Training Audit Hardening","",f"Marker: `{MARKER}`","",f"**Entscheidung: `{decision}`**","",f"- Statisches Adam-Resume mit aktiver Scale 128: `{checks['static_metadata_and_active_scale']}`.",f"- CPU-/CUDA-all-/Custom-RNG und Folgezug: `{checks['complete_rng_resume']}`.",f"- Event-Ketten-Training A→B, 64 Runden: `{checks['event_chain_training']}`.",f"- Unterlaufrettung: `{checks['underflow_rescue']}`.",f"- Finite-to-FP16-Overflow, Skip und Recovery: `{checks['finite_overflow']}`.",f"- C1a-Identität und numerische Hülle: `{checks['c1a_identity'] and checks['c1a_numerical_envelope']}`.",f"- Manipulationstests: {sum(x['passed'] for x in mutations)}/{len(mutations)} blockierten fail-closed.",f"- Historische A/B/B1/C/C1/C1a/D-Reports bytegleich: `{checks['historical_hashes']}`.",f"- Produktionscode unverändert: `{checks['production_unchanged']}`.",""]
(P/"PHASE3B1D1_TRAINING_AUDIT_HARDENING.md").write_text("\n".join(lines));print(decision)
