// TCNN_RDNA4_P3B1C_FP16_BACKWARD_001: isolated dX/dW hipBLASLt capability probe.
#include <hip/hip_fp16.h>
#include <hip/hip_runtime.h>
#include <hipblaslt/hipblaslt-ext.hpp>
#include <hipblaslt/hipblaslt.h>
#include <json/json.hpp>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
using json=nlohmann::json;
namespace {
constexpr const char* MARKER="TCNN_RDNA4_P3B1C_FP16_BACKWARD_001";constexpr size_t GUARD=256,MAX_WS=64ull<<20;
void hc(hipError_t s,const char*w){if(s!=hipSuccess)throw std::runtime_error{std::string(w)+": "+hipGetErrorString(s)};}void lc(hipblasStatus_t s,const char*w){if(s!=HIPBLAS_STATUS_SUCCESS)throw std::runtime_error{std::string(w)+": "+std::to_string((int)s)};}size_t cm(int64_t r,int64_t c,int64_t ld){return(size_t)r+c*ld;}
struct G{void*base=nullptr;size_t n;uint8_t fill,guard;G(size_t n_,uint8_t f,uint8_t g):n(n_),fill(f),guard(g){hc(hipMalloc(&base,GUARD+n+GUARD),"malloc guard");reset();}~G(){if(base)hipFree(base);}void*data(){return(char*)base+GUARD;}void reset(){std::vector<uint8_t>h(GUARD+n+GUARD,guard);std::fill(h.begin()+GUARD,h.begin()+GUARD+n,fill);hc(hipMemcpy(base,h.data(),h.size(),hipMemcpyHostToDevice),"reset");}json inspect(){std::vector<uint8_t>h(GUARD+n+GUARD);hc(hipMemcpy(h.data(),base,h.size(),hipMemcpyDeviceToHost),"inspect");return{{"prefix",std::all_of(h.begin(),h.begin()+GUARD,[&](auto v){return v==guard;})},{"suffix",std::all_of(h.end()-GUARD,h.end(),[&](auto v){return v==guard;})},{"unchanged",std::all_of(h.begin()+GUARD,h.end()-GUARD,[&](auto v){return v==fill;})}};}};
float pat(size_t i,int salt){return __half2float(__float2half((((int)(i*17+salt*13)%41)-20)*0.015625f));}
json probe(std::string dir,int64_t m,int64_t n,int64_t k,std::string dtype,int repeat){bool ta=dir[0]=='T',tb=dir[1]=='T',d16=dtype=="f16";int64_t ar=ta?k:m,ac=ta?m:k,br=tb?n:k,bc=tb?k:n;std::vector<__half>A(ar*ac),B(br*bc);for(size_t i=0;i<A.size();++i)A[i]=__float2half(pat(i,1));for(size_t i=0;i<B.size();++i)B[i]=__float2half(pat(i,2));std::vector<float>ref(m*n);for(int64_t c=0;c<n;++c)for(int64_t r=0;r<m;++r){float s=0;for(int64_t q=0;q<k;++q){float av=__half2float(A[ta?cm(q,r,ar):cm(r,q,ar)]),bv=__half2float(B[tb?cm(c,q,br):cm(q,c,br)]);s+=av*bv;}ref[cm(r,c,m)]=d16?__half2float(__float2half(s)):s;}
 void *da=nullptr,*db=nullptr,*dc=nullptr;hc(hipMalloc(&da,A.size()*2),"A");hc(hipMalloc(&db,B.size()*2),"B");size_t bytes=m*n*(d16?2:4);hc(hipMalloc(&dc,bytes),"C");hc(hipMemcpy(da,A.data(),A.size()*2,hipMemcpyHostToDevice),"copy A");hc(hipMemcpy(db,B.data(),B.size()*2,hipMemcpyHostToDevice),"copy B");hc(hipMemset(dc,0,bytes),"clear C");G out(bytes,0xa5,0x5a);hipblasLtHandle_t planning=nullptr,h[2]{};hipStream_t streams[2]{};hipblasLtMatmulDesc_t op=nullptr;hipblasLtMatrixLayout_t la=nullptr,lb=nullptr,lcc=nullptr,ld=nullptr;hipblasLtMatmulPreference_t pref=nullptr;lc(hipblasLtCreate(&planning),"planning");for(int i=0;i<2;++i){lc(hipblasLtCreate(&h[i]),"handle");hc(hipStreamCreate(&streams[i]),"stream");}auto dt=d16?HIP_R_16F:HIP_R_32F;lc(hipblasLtMatmulDescCreate(&op,HIPBLAS_COMPUTE_32F,HIP_R_32F),"desc");auto opa=ta?HIPBLAS_OP_T:HIPBLAS_OP_N,opb=tb?HIPBLAS_OP_T:HIPBLAS_OP_N;lc(hipblasLtMatmulDescSetAttribute(op,HIPBLASLT_MATMUL_DESC_TRANSA,&opa,sizeof(opa)),"ta");lc(hipblasLtMatmulDescSetAttribute(op,HIPBLASLT_MATMUL_DESC_TRANSB,&opb,sizeof(opb)),"tb");lc(hipblasLtMatrixLayoutCreate(&la,HIP_R_16F,ar,ac,ar),"la");lc(hipblasLtMatrixLayoutCreate(&lb,HIP_R_16F,br,bc,br),"lb");lc(hipblasLtMatrixLayoutCreate(&lcc,dt,m,n,m),"lc");lc(hipblasLtMatrixLayoutCreate(&ld,dt,m,n,m),"ld");lc(hipblasLtMatmulPreferenceCreate(&pref),"pref");uint64_t maxws=MAX_WS;lc(hipblasLtMatmulPreferenceSetAttribute(pref,HIPBLASLT_MATMUL_PREF_MAX_WORKSPACE_BYTES,&maxws,sizeof(maxws)),"ws pref");std::array<hipblasLtMatmulHeuristicResult_t,32>cs{};int count=0;auto hs=hipblasLtMatmulAlgoGetHeuristic(planning,op,la,lb,lcc,ld,pref,cs.size(),cs.data(),&count);int sel=-1;for(int i=0;i<count;++i)if(cs[i].state==HIPBLAS_STATUS_SUCCESS&&cs[i].workspaceSize<=MAX_WS){sel=i;break;}json result={{"marker",MARKER},{"direction",dir},{"m",m},{"n",n},{"k",k},{"d_type",dtype},{"repeat",repeat},{"heuristic_status",(int)hs},{"heuristic_count",count},{"selected",sel},{"compute","FP32"},{"a_type","FP16"},{"b_type","FP16"}};
 if(hs!=HIPBLAS_STATUS_SUCCESS||sel<0)result["state"]="UNSUPPORTED";else{auto&c=cs[sel];G ws(std::max<size_t>(c.workspaceSize,1),0xc3,0x7e);const float alpha=1,beta=0;std::vector<float>got;json launches=json::array();for(int l=0;l<6;++l){out.reset();int si=l%2;auto ms=hipblasLtMatmul(h[si],op,&alpha,da,la,db,lb,&beta,dc,lcc,out.data(),ld,&c.algo,c.workspaceSize?ws.data():nullptr,c.workspaceSize,streams[si]);auto ss=hipStreamSynchronize(streams[si]);launches.push_back({{"status",(int)ms},{"sync",(int)ss},{"stream",si},{"memory",out.inspect()}});if(ms==0&&ss==0){got.resize(m*n);if(d16){std::vector<__half>x(m*n);hc(hipMemcpy(x.data(),out.data(),bytes,hipMemcpyDeviceToHost),"D16");for(size_t i=0;i<x.size();++i)got[i]=__half2float(x[i]);}else hc(hipMemcpy(got.data(),out.data(),bytes,hipMemcpyDeviceToHost),"D32");}}double ma=0,mr=0,nume=0,den=0;for(size_t i=0;i<got.size();++i){double e=std::abs(got[i]-ref[i]);ma=std::max(ma,e);if(std::abs(ref[i])>1e-3)mr=std::max(mr,e/std::abs(ref[i]));nume+=e*e;den+=(double)ref[i]*ref[i];}result["state"]="EXECUTED";result["launches"]=launches;result["workspace_memory"]=ws.inspect();result["algorithm"]={{"index",hipblaslt_ext::getIndexFromAlgo(c.algo)},{"kernel",hipblaslt_ext::getKernelNameFromAlgo(planning,c.algo)},{"solution",hipblaslt_ext::getSolutionNameFromAlgo(planning,c.algo)},{"workspace",c.workspaceSize}};result["metrics"]={{"max_abs",ma},{"max_rel",mr},{"normalized_l2",std::sqrt(nume/std::max(den,1e-30))}};result["steady"]={{"new_handles",0},{"new_heuristics",0},{"new_descriptors",0},{"workspace_growth",0}};}
 if(pref)hipblasLtMatmulPreferenceDestroy(pref);if(ld)hipblasLtMatrixLayoutDestroy(ld);if(lcc)hipblasLtMatrixLayoutDestroy(lcc);if(lb)hipblasLtMatrixLayoutDestroy(lb);if(la)hipblasLtMatrixLayoutDestroy(la);if(op)hipblasLtMatmulDescDestroy(op);for(int i=0;i<2;++i){if(h[i])hipblasLtDestroy(h[i]);if(streams[i])hipStreamDestroy(streams[i]);}if(planning)hipblasLtDestroy(planning);if(dc)hipFree(dc);if(db)hipFree(db);if(da)hipFree(da);return result;}
}
int main(int argc,char**argv){json r={{"marker",MARKER}};try{if(argc!=8)throw std::runtime_error{"usage: probe DIR M N K f16|f32 REPEAT ROLE"};r=probe(argv[1],std::stoll(argv[2]),std::stoll(argv[3]),std::stoll(argv[4]),argv[5],std::stoi(argv[6]));r["role"]=argv[7];r["process_status"]="PASS";}catch(const std::exception&e){r["process_status"]="ERROR";r["error"]=e.what();}std::cout<<r.dump()<<"\n";return r.value("process_status","ERROR")=="PASS"?0:1;}
