/* TCNN_RDNA4_P3B1B_FP16_FORWARD_001: opt-in FP16 forward-only hipBLASLt MLP. */
#include <tiny-cuda-nn/common_host.h>
#include <tiny-cuda-nn/random.h>
#include <tiny-cuda-nn/networks/hipblaslt_mlp_fp16.h>
#include <hipblaslt/hipblaslt.h>
#include <atomic>
#include <cmath>
#include <cstring>
#include <memory>
#include <mutex>
#include <unordered_map>

namespace tcnn { namespace {
std::atomic<uint64_t> f_hits{0},f_misses{0},f_queries{0},f_handle_create{0},f_handle_reuse{0},f_desc{0},f_bias{0},f_relu{0};
void check(hipblasStatus_t s,const char* w){if(s!=HIPBLAS_STATUS_SUCCESS)throw std::runtime_error{fmt::format("HipBLASLtMLPFP16 {} failed: {}",w,(int)s)};}
enum class FEpi:uint8_t{Bias,ReluBias};
struct FKey {
	int device; uint32_t ar,ac,br,bc,dr,dc; bool ta,tb; FEpi epi;
	hipDataType a_type,b_type,c_type,d_type,bias_type,scale_type; hipblasComputeType_t compute_type;
	MatrixLayout a_layout,b_layout,d_layout;
	bool operator==(const FKey&o)const{return device==o.device&&ar==o.ar&&ac==o.ac&&br==o.br&&bc==o.bc&&dr==o.dr&&dc==o.dc&&ta==o.ta&&tb==o.tb&&epi==o.epi&&a_type==o.a_type&&b_type==o.b_type&&c_type==o.c_type&&d_type==o.d_type&&bias_type==o.bias_type&&scale_type==o.scale_type&&compute_type==o.compute_type&&a_layout==o.a_layout&&b_layout==o.b_layout&&d_layout==o.d_layout;}
};
struct FHash {size_t operator()(const FKey&k)const{size_t h=k.device;for(auto v:{k.ar,k.ac,k.br,k.bc,k.dr,k.dc})h=h*1099511628211ull^v;h=h*131u^((size_t)k.ta<<1)^((size_t)k.tb<<2)^((size_t)k.epi<<3);h=h*131u^(size_t)k.a_type^((size_t)k.b_type<<4)^((size_t)k.c_type<<8)^((size_t)k.d_type<<12)^((size_t)k.bias_type<<16)^((size_t)k.scale_type<<20)^((size_t)k.compute_type<<24);return h^((size_t)k.a_layout<<5)^((size_t)k.b_layout<<7)^((size_t)k.d_layout<<9);}};
void configure(hipblasLtMatmulDesc_t d,const FKey&k){hipblasOperation_t ta=k.ta?HIPBLAS_OP_T:HIPBLAS_OP_N,tb=k.tb?HIPBLAS_OP_T:HIPBLAS_OP_N;check(hipblasLtMatmulDescSetAttribute(d,HIPBLASLT_MATMUL_DESC_TRANSA,&ta,sizeof(ta)),"set TRANSA");check(hipblasLtMatmulDescSetAttribute(d,HIPBLASLT_MATMUL_DESC_TRANSB,&tb,sizeof(tb)),"set TRANSB");auto e=k.epi==FEpi::ReluBias?HIPBLASLT_EPILOGUE_RELU_BIAS:HIPBLASLT_EPILOGUE_BIAS;check(hipblasLtMatmulDescSetAttribute(d,HIPBLASLT_MATMUL_DESC_EPILOGUE,&e,sizeof(e)),"set EPILOGUE");}
struct FPlan {hipblasLtMatmulDesc_t desc=nullptr;hipblasLtMatrixLayout_t a=nullptr,b=nullptr,c=nullptr,d=nullptr;hipblasLtMatmulAlgo_t algo{};explicit FPlan(const FKey&k){check(hipblasLtMatmulDescCreate(&desc,k.compute_type,k.scale_type),"create plan descriptor");configure(desc,k);check(hipblasLtMatrixLayoutCreate(&a,k.a_type,k.ar,k.ac,k.ar),"create A layout");check(hipblasLtMatrixLayoutCreate(&b,k.b_type,k.br,k.bc,k.br),"create B layout");check(hipblasLtMatrixLayoutCreate(&c,k.c_type,k.dr,k.dc,k.dr),"create C layout");check(hipblasLtMatrixLayoutCreate(&d,k.d_type,k.dr,k.dc,k.dr),"create D layout");}~FPlan(){if(d)hipblasLtMatrixLayoutDestroy(d);if(c)hipblasLtMatrixLayoutDestroy(c);if(b)hipblasLtMatrixLayoutDestroy(b);if(a)hipblasLtMatrixLayoutDestroy(a);if(desc)hipblasLtMatmulDescDestroy(desc);}};
struct FHandle {hipStream_t stream=nullptr;hipblasLtHandle_t handle=nullptr;std::mutex mutex;~FHandle(){if(handle)hipblasLtDestroy(handle);}};
struct FDevice {hipblasLtHandle_t planning=nullptr;std::mutex mutex;std::unordered_map<FKey,std::shared_ptr<FPlan>,FHash> plans;std::unordered_map<uintptr_t,std::shared_ptr<FHandle>> handles;FDevice(){check(hipblasLtCreate(&planning),"create planning handle");}~FDevice(){handles.clear();plans.clear();if(planning)hipblasLtDestroy(planning);}};
FDevice& fdevice(int device){static std::mutex m;static std::unordered_map<int,std::unique_ptr<FDevice>> map;std::lock_guard<std::mutex>g{m};auto&r=map[device];if(!r)r=std::make_unique<FDevice>();return*r;}
std::shared_ptr<FHandle> fhandle(int device,hipStream_t stream){auto&d=fdevice(device);std::lock_guard<std::mutex>g{d.mutex};auto key=(uintptr_t)stream;auto i=d.handles.find(key);if(i!=d.handles.end()){++f_handle_reuse;return i->second;}if(d.handles.size()>=64)throw std::runtime_error{"HipBLASLtMLPFP16 execution-handle capacity exceeded."};auto h=std::make_shared<FHandle>();h->stream=stream;check(hipblasLtCreate(&h->handle),"create execution handle");d.handles.emplace(key,h);++f_handle_create;return h;}
std::shared_ptr<FPlan> fplan(const FKey&key){auto&d=fdevice(key.device);std::lock_guard<std::mutex>g{d.mutex};auto i=d.plans.find(key);if(i!=d.plans.end()){++f_hits;return i->second;}++f_misses;auto p=std::make_shared<FPlan>(key);hipblasLtMatmulPreference_t pref=nullptr;check(hipblasLtMatmulPreferenceCreate(&pref),"create preference");uint64_t ws=0;check(hipblasLtMatmulPreferenceSetAttribute(pref,HIPBLASLT_MATMUL_PREF_MAX_WORKSPACE_BYTES,&ws,sizeof(ws)),"set zero workspace");hipblasLtMatmulHeuristicResult_t c[32]{};int n=0;++f_queries;auto s=hipblasLtMatmulAlgoGetHeuristic(d.planning,p->desc,p->a,p->b,p->c,p->d,pref,32,c,&n);hipblasLtMatmulPreferenceDestroy(pref);check(s,"query heuristic");bool found=false;for(int j=0;j<n;++j)if(c[j].state==HIPBLAS_STATUS_SUCCESS&&c[j].workspaceSize==0){p->algo=c[j].algo;found=true;break;}if(!found)throw std::runtime_error{"HipBLASLtMLPFP16 found no exact zero-workspace FP16 plan."};d.plans.emplace(key,p);return p;}
bool width_ok(uint32_t w){return w==16||w==32||w==64||w==128;}
void contiguous(const GPUMatrixDynamic<__half>&x){if(x.layout()!=MatrixLayout::ColumnMajor||x.stride()!=x.m())throw std::runtime_error{"HipBLASLtMLPFP16 requires contiguous ColumnMajor matrices; no fallback is permitted."};}
} // namespace

struct HipBLASLtMLPFP16::DescriptorState {struct Entry{FKey key;const __half*bias;hipblasLtMatmulDesc_t desc=nullptr;~Entry(){if(desc)hipblasLtMatmulDescDestroy(desc);--f_desc;}};std::mutex mutex;std::vector<std::shared_ptr<Entry>> entries;hipblasLtMatmulDesc_t get(const FKey&key,const __half*bias){std::lock_guard<std::mutex>g{mutex};for(auto&e:entries)if(e->key==key&&e->bias==bias)return e->desc;auto e=std::make_shared<Entry>();e->key=key;e->bias=bias;check(hipblasLtMatmulDescCreate(&e->desc,key.compute_type,key.scale_type),"create launch descriptor");configure(e->desc,key);const void*p=bias;check(hipblasLtMatmulDescSetAttribute(e->desc,HIPBLASLT_MATMUL_DESC_BIAS_POINTER,&p,sizeof(p)),"set bias pointer");int32_t type=(int32_t)key.bias_type;check(hipblasLtMatmulDescSetAttribute(e->desc,HIPBLASLT_MATMUL_DESC_BIAS_DATA_TYPE,&type,sizeof(type)),"set bias type");entries.emplace_back(e);++f_desc;return e->desc;}};

uint64_t hipblaslt_fp16_cache_hits(){return f_hits;}uint64_t hipblaslt_fp16_cache_misses(){return f_misses;}uint64_t hipblaslt_fp16_heuristic_queries(){return f_queries;}uint64_t hipblaslt_fp16_execution_handle_creations(){return f_handle_create;}uint64_t hipblaslt_fp16_execution_handle_reuses(){return f_handle_reuse;}uint64_t hipblaslt_fp16_descriptor_count(){return f_desc;}uint64_t hipblaslt_fp16_bias_launches(){return f_bias;}uint64_t hipblaslt_fp16_relu_bias_launches(){return f_relu;}
// All selected Phase-3B1-B plans are contractually zero-workspace.
uint64_t hipblaslt_fp16_scratch_bytes_live(){return 0;}uint64_t hipblaslt_fp16_scratch_bytes_peak(){return 0;}
uint64_t hipblaslt_fp16_cache_size(){int d=0;CUDA_CHECK_THROW(hipGetDevice(&d));auto&x=fdevice(d);std::lock_guard<std::mutex>g{x.mutex};return x.plans.size();}
uint64_t hipblaslt_fp16_execution_handle_count(){int d=0;CUDA_CHECK_THROW(hipGetDevice(&d));auto&x=fdevice(d);std::lock_guard<std::mutex>g{x.mutex};return x.handles.size();}

HipBLASLtMLPFP16::HipBLASLtMLPFP16(uint32_t input,uint32_t hidden,uint32_t output,uint32_t layers,Activation activation,Activation output_activation):m_input_width{input},m_hidden_width{hidden},m_output_width{output},m_n_hidden_layers{layers},m_activation{activation},m_output_activation{output_activation}{int d=0;CUDA_CHECK_THROW(hipGetDevice(&d));hipDeviceProp_t p{};CUDA_CHECK_THROW(hipGetDeviceProperties(&p,d));if(std::strcmp(p.gcnArchName,"gfx1201")!=0)throw std::runtime_error{"HipBLASLtMLPFP16 supports gfx1201 only."};if(!width_ok(input)||!width_ok(hidden)||!width_ok(output))throw std::runtime_error{"HipBLASLtMLPFP16 supports input, hidden, and output widths 16, 32, 64, or 128 only."};if(layers!=1&&layers!=2&&layers!=4)throw std::runtime_error{"HipBLASLtMLPFP16 supports 1, 2, or 4 hidden layers."};if((activation!=Activation::None&&activation!=Activation::ReLU)||(output_activation!=Activation::None&&output_activation!=Activation::ReLU))throw std::runtime_error{"HipBLASLtMLPFP16 supports None and ReLU only."};for(uint32_t i=0;i<=layers;++i){uint32_t in=i?hidden:input,out=i==layers?output:hidden;size_t w=m_total_n_params,b=w+(size_t)in*out;m_layers.push_back({in,out,w,b});m_total_n_params=b+out;}m_descriptors=std::make_unique<DescriptorState>();}
HipBLASLtMLPFP16::~HipBLASLtMLPFP16()=default;
void HipBLASLtMLPFP16::linear(hipStream_t stream,const GPUMatrixDynamic<__half>&input,const __half*weights,const __half*bias,GPUMatrixDynamic<__half>&output,uint32_t in,uint32_t out,Activation activation){contiguous(input);contiguous(output);if(input.n()==0)throw std::runtime_error{"HipBLASLtMLPFP16 rejects zero-batch input explicitly."};int device=0;CUDA_CHECK_THROW(hipGetDevice(&device));FKey key{device,in,out,in,input.n(),out,input.n(),true,false,activation==Activation::ReLU?FEpi::ReluBias:FEpi::Bias,HIP_R_16F,HIP_R_16F,HIP_R_16F,HIP_R_16F,HIP_R_16F,HIP_R_32F,HIPBLAS_COMPUTE_32F,MatrixLayout::ColumnMajor,MatrixLayout::ColumnMajor,MatrixLayout::ColumnMajor};auto plan=fplan(key);auto desc=m_descriptors->get(key,bias);auto handle=fhandle(device,stream);const float alpha=1,beta=0;std::lock_guard<std::mutex>g{handle->mutex};check(hipblasLtMatmul(handle->handle,desc,&alpha,weights,plan->a,input.data(),plan->b,&beta,output.data(),plan->c,output.data(),plan->d,&plan->algo,nullptr,0,stream),"FP16 forward matmul");if(activation==Activation::ReLU)++f_relu;else++f_bias;}
void HipBLASLtMLPFP16::inference_mixed_precision_impl(hipStream_t stream,const GPUMatrixDynamic<__half>&input,GPUMatrixDynamic<__half>&output,bool inference){std::vector<GPUMatrixDynamic<__half>> buffers;buffers.reserve(m_n_hidden_layers);auto current=&input;const auto*p=selected_params(inference);if(!p)throw std::runtime_error{"HipBLASLtMLPFP16 parameters were not provided."};for(uint32_t i=0;i<m_n_hidden_layers;++i){buffers.emplace_back(m_hidden_width,input.n(),stream,MatrixLayout::ColumnMajor);auto&l=m_layers[i];linear(stream,*current,p+l.weights,p+l.bias,buffers.back(),l.in,l.out,m_activation);current=&buffers.back();}auto&l=m_layers.back();linear(stream,*current,p+l.weights,p+l.bias,output,l.in,l.out,m_output_activation);}
std::unique_ptr<Context> HipBLASLtMLPFP16::forward_impl(hipStream_t stream,const GPUMatrixDynamic<__half>&input,GPUMatrixDynamic<__half>*output,bool inference,bool){auto f=std::make_unique<ForwardContext>();f->activations.reserve(m_n_hidden_layers);auto current=&input;const auto*p=selected_params(inference);for(uint32_t i=0;i<m_n_hidden_layers;++i){f->activations.emplace_back(m_hidden_width,input.n(),stream,MatrixLayout::ColumnMajor);auto&l=m_layers[i];linear(stream,*current,p+l.weights,p+l.bias,f->activations.back(),l.in,l.out,m_activation);current=&f->activations.back();}if(!output){f->owned_output={m_output_width,input.n(),stream,MatrixLayout::ColumnMajor};output=&f->owned_output;}auto&l=m_layers.back();linear(stream,*current,p+l.weights,p+l.bias,*output,l.in,l.out,m_output_activation);return f;}
void HipBLASLtMLPFP16::backward_impl(hipStream_t,const Context&,const GPUMatrixDynamic<__half>&,const GPUMatrixDynamic<__half>&,const GPUMatrixDynamic<__half>&,GPUMatrixDynamic<__half>*,bool,GradientMode){throw std::runtime_error{"HipBLASLtMLPFP16 is forward-only in Phase 3B1-B; backward is unsupported."};}
void HipBLASLtMLPFP16::initialize_params(pcg32&r,float*p,float scale){for(auto&l:m_layers){float bound=scale*std::sqrt(6.f/(l.in+l.out));generate_random_uniform<float>(r,(size_t)l.in*l.out,p+l.weights,-bound,bound);CUDA_CHECK_THROW(hipMemset(p+l.bias,0,l.out*sizeof(float)));}}
std::vector<std::pair<uint32_t,uint32_t>> HipBLASLtMLPFP16::layer_sizes()const{std::vector<std::pair<uint32_t,uint32_t>>r;for(auto&l:m_layers)r.emplace_back(l.in,l.out);return r;}uint32_t HipBLASLtMLPFP16::width(uint32_t l)const{if(l>=m_n_hidden_layers)throw std::runtime_error{"HipBLASLtMLPFP16 layer out of range."};return m_hidden_width;}std::pair<const __half*,MatrixLayout> HipBLASLtMLPFP16::forward_activations(const Context&c,uint32_t l)const{if(l>=m_n_hidden_layers)throw std::runtime_error{"HipBLASLtMLPFP16 activation out of range."};auto&f=dynamic_cast<const ForwardContext&>(c);return{f.activations[l].data(),f.activations[l].layout()};}json HipBLASLtMLPFP16::hyperparams()const{return{{"otype","HipBLASLtMLPFP16"},{"activation",to_string(m_activation)},{"output_activation",to_string(m_output_activation)},{"n_neurons",m_hidden_width},{"n_hidden_layers",m_n_hidden_layers},{"bias",true},{"operand_precision","Fp16"},{"accumulation_precision","Fp32"},{"hidden_output_precision","Fp16"},{"final_output_precision","Fp16"},{"backward",false}};}
} // namespace tcnn
